const mockCategories = [
  {
    id: "leafy",
    nameKey: "leafy",
    icon: "🥬",
    items: ["Spinach", "Coriander", "Mint", "Fenugreek"]
  },
  {
    id: "root",
    nameKey: "root",
    icon: "🥕",
    items: ["Carrot", "Radish", "Beetroot", "Potato", "Sweet Potato", "Onion", "Garlic"]
  },
  {
    id: "seasonal",
    nameKey: "seasonal",
    icon: "🎃",
    items: ["Pumpkin", "Cauliflower", "Green Peas", "Beans", "Bitter Gourd"]
  },
  {
    id: "spices",
    nameKey: "spices",
    icon: "🌶️",
    items: ["Red Chilli", "Green Chilli", "Ginger", "Turmeric"]
  },
  {
    id: "fruiting",
    nameKey: "fruiting",
    icon: "🍅",
    items: ["Tomato", "Brinjal", "Ladies Finger", "Drumstick", "Ivy Gourd", "Capsicum", "Bottle Gourd"]
  }
];

const mockProducts = [
  // CATEGORY 1: LEAFY VEGETABLES (4)
  {
    id: "prod-1",
    name: "Organic Palak (Spinach)",
    nameEn: "Spinach",
    nameTe: "పాలకూర",
    nameHi: "पालक",
    category: "leafy",
    cropItem: "Spinach",
    image: "./images/spinach.jpg",
    price: 22,
    oldPrice: 26,
    unit: "kg",
    availableQty: 150,
    qualityGrade: "Grade A",
    farmerId: "f-102",
    farmerName: "Lakshmi Narayana",
    farmerType: "Krishna Farmer Co-op",
    location: "Tenali, Guntur District",
    distanceKm: 1.2,
    rating: 4.9,
    verified: true,
    harvestDate: "2026-08-29",
    freshness: "Harvested Today Morning",
    description: "Crisp green tender spinach leaves, zero pesticide sprays. Packed in clean bunches."
  },
  {
    id: "prod-2",
    name: "Fresh Green Coriander (Kothimeera)",
    nameEn: "Coriander",
    nameTe: "కొత్తిమీర",
    nameHi: "धनिया",
    category: "leafy",
    cropItem: "Coriander",
    image: "./images/coriander.jpg",
    price: 30,
    oldPrice: 35,
    unit: "kg",
    availableQty: 100,
    qualityGrade: "Grade A",
    farmerId: "f-101",
    farmerName: "Ramesh Reddy",
    farmerType: "Individual Farmer",
    location: "Kankipadu, Krishna District",
    distanceKm: 1.5,
    rating: 4.8,
    verified: true,
    harvestDate: "2026-08-29",
    freshness: "Farm Fresh",
    description: "Aromatic cilantro/coriander bunches harvested fresh with strong herbal fragrance."
  },
  {
    id: "prod-3",
    name: "Organic Mint Leaves (Pudina)",
    nameEn: "Mint",
    nameTe: "పుదీనా",
    nameHi: "पुदीना",
    category: "leafy",
    cropItem: "Mint",
    image: "./images/curry leaves.jpg",
    price: 35,
    oldPrice: 40,
    unit: "kg",
    availableQty: 80,
    qualityGrade: "Grade A",
    farmerId: "f-103",
    farmerName: "Venkata Rao",
    farmerType: "Individual Farmer",
    location: "Nuzvid, Krishna District",
    distanceKm: 2.1,
    rating: 4.75,
    verified: true,
    harvestDate: "2026-08-29",
    freshness: "Harvested Today",
    description: "Intensely fragrant mint leaves ideal for culinary, tea, and juice extraction."
  },
  {
    id: "prod-4",
    name: "Tender Fenugreek Leaves (Methi)",
    nameEn: "Fenugreek",
    nameTe: "మెంతులు",
    nameHi: "मेथी",
    category: "leafy",
    cropItem: "Fenugreek",
    image: "./images/mathi.jpg",
    price: 28,
    oldPrice: 32,
    unit: "kg",
    availableQty: 120,
    qualityGrade: "Grade A",
    farmerId: "f-105",
    farmerName: "Subbaiah Chowdary",
    farmerType: "Rythu Sangh",
    location: "Gannavaram, Krishna District",
    distanceKm: 1.8,
    rating: 4.85,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Fresh Plucked",
    description: "Nutritious small-leaf methi grown naturally with high iron content."
  },

  // CATEGORY 2: ROOT VEGETABLES (7)
  {
    id: "prod-5",
    name: "Organic Farm Carrots",
    nameEn: "Carrot",
    nameTe: "క్యారెట్",
    nameHi: "गाजर",
    category: "root",
    cropItem: "Carrot",
    image: "./images/carrot.jpg",
    price: 36,
    oldPrice: 40,
    unit: "kg",
    availableQty: 400,
    qualityGrade: "Grade A",
    farmerId: "f-102",
    farmerName: "Lakshmi Narayana",
    farmerType: "Krishna Farmer Co-op",
    location: "Tenali, Guntur District",
    distanceKm: 2.2,
    rating: 4.9,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Farm Fresh Washed",
    description: "Crunchy bright orange carrots rich in vitamin A. Perfect for salads and cooking."
  },
  {
    id: "prod-6",
    name: "Fresh White Radish (Mullangi)",
    nameEn: "Radish",
    nameTe: "ముల్లంగి",
    nameHi: "मूली",
    category: "root",
    cropItem: "Radish",
    image: "./images/radish.jpg",
    price: 25,
    oldPrice: 30,
    unit: "kg",
    availableQty: 300,
    qualityGrade: "Grade A",
    farmerId: "f-106",
    farmerName: "Srinivasulu M",
    farmerType: "Individual Farmer",
    location: "Vuyyuru, Krishna District",
    distanceKm: 2.9,
    rating: 4.7,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Cleaned Roots",
    description: "Firm, crisp white radish harvested directly from fertile riverbed soils."
  },
  {
    id: "prod-7",
    name: "Deep Red Farm Beetroot",
    nameEn: "Beetroot",
    nameTe: "బీట్‌రూట్",
    nameHi: "चुकंदर",
    category: "root",
    cropItem: "Beetroot",
    image: "./images/beetroot.jpg",
    price: 32,
    oldPrice: 38,
    unit: "kg",
    availableQty: 250,
    qualityGrade: "Grade A",
    farmerId: "f-101",
    farmerName: "Ramesh Reddy",
    farmerType: "Individual Farmer",
    location: "Kankipadu, Krishna District",
    distanceKm: 3.1,
    rating: 4.8,
    verified: true,
    harvestDate: "2026-08-27",
    freshness: "Fresh Soil Harvest",
    description: "Sweet, juicy deep purple-red beetroots excellent for juice and salads."
  },
  {
    id: "prod-8",
    name: "Fresh Yellow Potato (Aloo)",
    nameEn: "Potato",
    nameTe: "బంగాళాదుంప",
    nameHi: "आलू",
    category: "root",
    cropItem: "Potato",
    image: "./images/potato.jpg",
    price: 26,
    oldPrice: 30,
    unit: "kg",
    availableQty: 1500,
    qualityGrade: "Grade A",
    farmerId: "f-103",
    farmerName: "Venkata Rao",
    farmerType: "Individual Farmer",
    location: "Nuzvid, Krishna District",
    distanceKm: 2.5,
    rating: 4.75,
    verified: true,
    harvestDate: "2026-08-26",
    freshness: "Cured Storage Potato",
    description: "Smooth-skinned, high-starch potatoes suitable for culinary use and bulk processing."
  },
  {
    id: "prod-9",
    name: "Organic Sweet Potato (Chilagada)",
    nameEn: "Sweet Potato",
    nameTe: "చిలగడదుంప",
    nameHi: "शकरकंद",
    category: "root",
    cropItem: "Sweet Potato",
    image: "./images/sweetpotato.jpg",
    price: 40,
    oldPrice: 48,
    unit: "kg",
    availableQty: 350,
    qualityGrade: "Grade A",
    farmerId: "f-105",
    farmerName: "Subbaiah Chowdary",
    farmerType: "Rythu Sangh",
    location: "Gannavaram, Krishna District",
    distanceKm: 3.8,
    rating: 4.85,
    verified: true,
    harvestDate: "2026-08-27",
    freshness: "Fresh Harvested",
    description: "Naturally sweet orange-fleshed sweet potatoes loaded with complex carbohydrates."
  },
  {
    id: "prod-10",
    name: "Nashik Quality Red Onion",
    nameEn: "Onion",
    nameTe: "ఉల్లిపాయ",
    nameHi: "प्याज",
    category: "root",
    cropItem: "Onion",
    image: "./images/onion.jpg",
    price: 34,
    oldPrice: 38,
    unit: "kg",
    availableQty: 1200,
    qualityGrade: "Grade A",
    farmerId: "f-103",
    farmerName: "Venkata Rao",
    farmerType: "Individual Farmer",
    location: "Nuzvid, Krishna District",
    distanceKm: 3.4,
    rating: 4.7,
    verified: true,
    harvestDate: "2026-08-25",
    freshness: "Sun Cured Produce",
    description: "Firm, dry skin red onions with high storage stability. Ideal for bulk commercial buyers."
  },
  {
    id: "prod-11",
    name: "Farm Fresh Garlic Bulbs (Vellulli)",
    nameEn: "Garlic",
    nameTe: "వెల్లుల్లి",
    nameHi: "लहसुन",
    category: "root",
    cropItem: "Garlic",
    image: "./images/garlic.jpg",
    price: 140,
    oldPrice: 160,
    unit: "kg",
    availableQty: 200,
    qualityGrade: "Grade A",
    farmerId: "f-104",
    farmerName: "Guntur Chilli FPO",
    farmerType: "FPO / Organization",
    location: "Duggirala, Guntur District",
    distanceKm: 4.2,
    rating: 4.9,
    verified: true,
    harvestDate: "2026-08-24",
    freshness: "Dry Cured Bulbs",
    description: "Large clove white garlic with strong aroma and long shelf life."
  },

  // CATEGORY 3: SEASONAL VEGETABLES (5)
  {
    id: "prod-12",
    name: "Golden Farm Pumpkin (Gummadi)",
    nameEn: "Pumpkin",
    nameTe: "గుమ్మడికాయ",
    nameHi: "कद्दू",
    category: "seasonal",
    cropItem: "Pumpkin",
    image: "./images/pumpkin.jpg",
    price: 20,
    oldPrice: 24,
    unit: "kg",
    availableQty: 600,
    qualityGrade: "Grade A",
    farmerId: "f-101",
    farmerName: "Ramesh Reddy",
    farmerType: "Individual Farmer",
    location: "Kankipadu, Krishna District",
    distanceKm: 4.8,
    rating: 4.8,
    verified: true,
    harvestDate: "2026-08-26",
    freshness: "Vine Ripened",
    description: "Mature yellow-orange sweet pumpkins harvested directly from vine."
  },
  {
    id: "prod-13",
    name: "Crisp White Cauliflower",
    nameEn: "Cauliflower",
    nameTe: "కాలీఫ్లవర్",
    nameHi: "फूलगोभी",
    category: "seasonal",
    cropItem: "Cauliflower",
    image: "./images/cauliflower.jpg",
    price: 35,
    oldPrice: 42,
    unit: "kg",
    availableQty: 300,
    qualityGrade: "Grade A",
    farmerId: "f-102",
    farmerName: "Lakshmi Narayana",
    farmerType: "Krishna Farmer Co-op",
    location: "Tenali, Guntur District",
    distanceKm: 3.9,
    rating: 4.85,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Fresh Curd",
    description: "Tightly packed white cauliflower heads surrounded by fresh green protective leaves."
  },
  {
    id: "prod-14",
    name: "Fresh Green Peas (Pachi Batani)",
    nameEn: "Green Peas",
    nameTe: "పచ్చి బఠానీలు",
    nameHi: "हरी मटर",
    category: "seasonal",
    cropItem: "Green Peas",
    image: "./images/green peas.jpg",
    price: 48,
    oldPrice: 55,
    unit: "kg",
    availableQty: 250,
    qualityGrade: "Grade A",
    farmerId: "f-105",
    farmerName: "Subbaiah Chowdary",
    farmerType: "Rythu Sangh",
    location: "Gannavaram, Krishna District",
    distanceKm: 4.5,
    rating: 4.75,
    verified: true,
    harvestDate: "2026-08-29",
    freshness: "Plucked Today",
    description: "Sweet, tender green pea pods full of fresh kernels. Cleaned and hand sorted."
  },
  {
    id: "prod-15",
    name: "Fresh Green Cabbage (Patta Gobi)",
    nameEn: "Cabbage",
    nameTe: "క్యాబేజీ",
    nameHi: "पत्ता गोभी",
    category: "seasonal",
    cropItem: "Cabbage",
    image: "./images/cabbage.jpg",
    price: 32,
    oldPrice: 38,
    unit: "kg",
    availableQty: 200,
    qualityGrade: "Grade A",
    farmerId: "f-106",
    farmerName: "Srinivasulu M",
    farmerType: "Individual Farmer",
    location: "Nunna, Krishna District",
    distanceKm: 3.5,
    rating: 4.7,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Tender Heads",
    description: "Farm fresh crisp green cabbage heads packed with essential nutrients."
  },
  {
    id: "prod-16",
    name: "Fresh Bitter Gourd (Kakarakaya)",
    nameEn: "Bitter Gourd",
    nameTe: "కాకరకాయ",
    nameHi: "करेला",
    category: "seasonal",
    cropItem: "Bitter Gourd",
    image: "./images/bittergourd.jpg",
    price: 36,
    oldPrice: 42,
    unit: "kg",
    availableQty: 180,
    qualityGrade: "Grade A",
    farmerId: "f-101",
    farmerName: "Ramesh Reddy",
    farmerType: "Individual Farmer",
    location: "Kankipadu, Krishna District",
    distanceKm: 2.6,
    rating: 4.8,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Dark Green Harvest",
    description: "Firm, dark green textured bitter gourds known for blood purification properties."
  },

  // CATEGORY 4: INDIAN SPICES (4)
  {
    id: "prod-17",
    name: "Colocasia / Taro Root (Chamadumpa)",
    nameEn: "Colocasia",
    nameTe: "చామదుంప",
    nameHi: "अरबी",
    category: "root",
    cropItem: "Colocasia",
    image: "./images/colocasia.jpg",
    price: 45,
    oldPrice: 52,
    unit: "kg",
    availableQty: 300,
    qualityGrade: "Grade A",
    farmerId: "f-104",
    farmerName: "Krishna Farmer Co-op",
    farmerType: "FPO / Organization",
    location: "Penamaluru, Krishna District",
    distanceKm: 2.8,
    rating: 4.95,
    verified: true,
    harvestDate: "2026-08-20",
    freshness: "Fresh Soil Harvest",
    description: "Premium quality nutrient-rich taro roots carefully harvested from river soils."
  },
  {
    id: "prod-18",
    name: "Guntur Hot Green Chillies (Pachi Mirapa)",
    nameEn: "Green Chilli",
    nameTe: "పచ్చిమిర్చి",
    nameHi: "हरी मिर्च",
    category: "spices",
    cropItem: "Green Chilli",
    image: "./images/green-chill.jpg",
    price: 45,
    oldPrice: 52,
    unit: "kg",
    availableQty: 350,
    qualityGrade: "Grade A",
    farmerId: "f-104",
    farmerName: "Guntur Chilli FPO",
    farmerType: "FPO / Organization",
    location: "Mirchi Yard, Guntur",
    distanceKm: 5.2,
    rating: 4.88,
    verified: true,
    harvestDate: "2026-08-29",
    freshness: "Fresh Plucked",
    description: "Bright green glossy chillies with high heat quotient. Freshly plucked daily."
  },
  {
    id: "prod-19",
    name: "Fresh Organic Ginger (Allam)",
    nameEn: "Ginger",
    nameTe: "అల్లం",
    nameHi: "अदरक",
    category: "spices",
    cropItem: "Ginger",
    image: "./images/ginger.jpg",
    price: 90,
    oldPrice: 105,
    unit: "kg",
    availableQty: 220,
    qualityGrade: "Grade A",
    farmerId: "f-103",
    farmerName: "Venkata Rao",
    farmerType: "Individual Farmer",
    location: "Nuzvid, Krishna District",
    distanceKm: 3.7,
    rating: 4.82,
    verified: true,
    harvestDate: "2026-08-26",
    freshness: "Washed Rhizomes",
    description: "Aromatic spicy ginger roots grown without synthetic chemicals."
  },
  {
    id: "prod-20",
    name: "Raw Organic Turmeric Rhizomes",
    nameEn: "Turmeric",
    nameTe: "పసుపు",
    nameHi: "हल्दी",
    category: "spices",
    cropItem: "Turmeric",
    image: "./images/Turmeric.jpg",
    price: 110,
    oldPrice: 130,
    unit: "kg",
    availableQty: 400,
    qualityGrade: "Grade A",
    farmerId: "f-104",
    farmerName: "Guntur Chilli FPO",
    farmerType: "FPO / Organization",
    location: "Duggirala, Guntur District",
    distanceKm: 5.8,
    rating: 4.92,
    verified: true,
    harvestDate: "2026-08-22",
    freshness: "High Curcumin Grade",
    description: "High curcumin content raw turmeric fingers directly from famous Duggirala belt."
  },

  // CATEGORY 5: FRUITING VEGETABLES (7)
  {
    id: "prod-21",
    name: "Fresh Farm Red Tomato (Tamata)",
    nameEn: "Tomato",
    nameTe: "టమాటా",
    nameHi: "टमाटर",
    category: "fruiting",
    cropItem: "Tomato",
    image: "./images/tomata.jpg",
    price: 28,
    oldPrice: 32,
    unit: "kg",
    availableQty: 500,
    qualityGrade: "Grade A",
    farmerId: "f-101",
    farmerName: "Ramesh Reddy",
    farmerType: "Individual Farmer",
    location: "Kankipadu, Krishna District",
    distanceKm: 2.4,
    rating: 4.8,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Harvested Yesterday",
    description: "Naturally ripened juicy red tomatoes grown using micro-drip irrigation. Excellent shelf life and high lycopene content."
  },
  {
    id: "prod-22",
    name: "Country Purple Brinjal (Vankaya)",
    nameEn: "Brinjal",
    nameTe: "వంకాయ",
    nameHi: "बैंगन",
    category: "fruiting",
    cropItem: "Brinjal",
    image: "./images/brinjal.jpg",
    price: 24,
    oldPrice: 28,
    unit: "kg",
    availableQty: 350,
    qualityGrade: "Grade A",
    farmerId: "f-106",
    farmerName: "Srinivasulu M",
    farmerType: "Individual Farmer",
    location: "Vuyyuru, Krishna District",
    distanceKm: 4.1,
    rating: 4.65,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Fresh Plucked",
    description: "Glossy purple medium-sized brinjals. Tender seedless texture inside."
  },
  {
    id: "prod-23",
    name: "Tender Okra (Ladies Finger)",
    nameEn: "Ladies Finger",
    nameTe: "బెండకాయ",
    nameHi: "भिंडी",
    category: "fruiting",
    cropItem: "Ladies Finger",
    image: "./images/LadiesFinger.jpg",
    price: 32,
    oldPrice: 36,
    unit: "kg",
    availableQty: 280,
    qualityGrade: "Grade A",
    farmerId: "f-102",
    farmerName: "Lakshmi Narayana",
    farmerType: "Krishna Farmer Co-op",
    location: "Tenali, Guntur District",
    distanceKm: 2.3,
    rating: 4.85,
    verified: true,
    harvestDate: "2026-08-29",
    freshness: "Morning Harvest",
    description: "Dark green tender ladies finger pods. Easy snap quality with low seeds."
  },
  {
    id: "prod-24",
    name: "Fresh Ridge Gourd (Beerakaya)",
    nameEn: "Ridge Gourd",
    nameTe: "బీరకాయ",
    nameHi: "तुरई",
    category: "seasonal",
    cropItem: "Ridge Gourd",
    image: "./images/ridge ground.jpg",
    price: 38,
    oldPrice: 45,
    unit: "kg",
    availableQty: 190,
    qualityGrade: "Grade A",
    farmerId: "f-105",
    farmerName: "Subbaiah Chowdary",
    farmerType: "Rythu Sangh",
    location: "Gannavaram, Krishna District",
    distanceKm: 3.2,
    rating: 4.9,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Tender Farm Harvest",
    description: "Tender, moisture-rich ridge gourds harvested fresh from riverbed farms."
  },
  {
    id: "prod-25",
    name: "Crisp Green Cucumber (Dosakaya / Kheera)",
    nameEn: "Cucumber",
    nameTe: "దోసకాయ",
    nameHi: "खीरा",
    category: "fruiting",
    cropItem: "Cucumber",
    image: "./images/cucumber.jpg",
    price: 30,
    oldPrice: 35,
    unit: "kg",
    availableQty: 220,
    qualityGrade: "Grade A",
    farmerId: "f-101",
    farmerName: "Ramesh Reddy",
    farmerType: "Individual Farmer",
    location: "Poranki, Krishna District",
    distanceKm: 1.8,
    rating: 4.75,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Fresh Harvested",
    description: "Crunchy, refreshing green cucumbers grown with organic farm practices."
  },
  {
    id: "prod-26",
    name: "Green Farm Capsicum (Bell Pepper)",
    nameEn: "Capsicum",
    nameTe: "క్యాప్సికమ్",
    nameHi: "शिमला मिर्च",
    category: "fruiting",
    cropItem: "Capsicum",
    image: "./images/Capsicum.jpg",
    price: 45,
    oldPrice: 55,
    unit: "kg",
    availableQty: 260,
    qualityGrade: "Grade A",
    farmerId: "f-102",
    farmerName: "Lakshmi Narayana",
    farmerType: "Krishna Farmer Co-op",
    location: "Tenali, Guntur District",
    distanceKm: 3.6,
    rating: 4.88,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Polyhouse Grown",
    description: "Thick-walled crunchy green bell peppers grown under climate-controlled polyhouse."
  },
  {
    id: "prod-27",
    name: "Tender Green Bottle Gourd (Sorakaya)",
    nameEn: "Bottle Gourd",
    nameTe: "సొరకాయ",
    nameHi: "लौकी",
    category: "fruiting",
    cropItem: "Bottle Gourd",
    image: "./images/bottle ground.jpg",
    price: 22,
    oldPrice: 26,
    unit: "kg",
    availableQty: 400,
    qualityGrade: "Grade A",
    farmerId: "f-106",
    farmerName: "Srinivasulu M",
    farmerType: "Individual Farmer",
    location: "Vuyyuru, Krishna District",
    distanceKm: 2.7,
    rating: 4.7,
    verified: true,
    harvestDate: "2026-08-28",
    freshness: "Fresh Plucked",
    description: "Light green cylindrical bottle gourds with high moisture content and soft skin."
  }
];

const mockFarmers = [
  {
    id: "f-101",
    name: "Ramesh Reddy",
    mobile: "+91 98480 12345",
    location: "Kankipadu Village, Krishna District, AP",
    farmName: "Reddy Organic Greens Farm",
    farmerType: "Individual Farmer",
    fpoName: "",
    verificationStatus: "verified",
    rating: 4.8,
    totalSalesKg: 14500,
    buyersCount: 28,
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=400&q=80"
  },
  {
    id: "f-102",
    name: "Lakshmi Narayana",
    mobile: "+91 94401 67890",
    location: "Tenali, Guntur District, AP",
    farmName: "Krishna Farmers Producer Org",
    farmerType: "FPO / Organization",
    fpoName: "Krishna Farmers Co-op",
    verificationStatus: "verified",
    rating: 4.9,
    totalSalesKg: 42000,
    buyersCount: 65,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80"
  }
];

const mockBuyers = [
  {
    id: "b-201",
    name: "FreshMart Wholesale",
    type: "Wholesaler / Bulk Buyer",
    rating: 4.8,
    distanceKm: 18,
    wantsQty: 300,
    offerPrice: 29,
    matchScore: 94,
    matchReason: "Needs 300 kg Grade A Tomatoes within 20 km. Verified top buyer."
  },
  {
    id: "b-202",
    name: "Delta Agro Processors",
    type: "Processor / Industry",
    rating: 4.7,
    distanceKm: 25,
    wantsQty: 500,
    offerPrice: 28.5,
    matchScore: 89,
    matchReason: "Requires 500 kg for ketchup processing. High volume buyer."
  },
  {
    id: "b-203",
    name: "Coastal Retailers Co-op",
    type: "Retailer",
    rating: 4.9,
    distanceKm: 12,
    wantsQty: 200,
    offerPrice: 28,
    matchScore: 82,
    matchReason: "Proximity 12 km, daily pickup schedule."
  }
];

const mockOrders = [
  {
    id: "AGC1024",
    productName: "Fresh Farm Red Tomato",
    category: "fruiting",
    quantity: 100,
    unit: "kg",
    unitPrice: 28,
    totalAmount: 2800,
    deliveryFee: 65,
    grandTotal: 2865,
    farmerName: "Ramesh Reddy",
    buyerName: "Vijayawada Fresh Mart",
    status: "in_transit",
    deliveryStatus: "In Transit",
    estimatedArrival: "4:30 PM",
    distanceKm: 18,
    routeEfficiency: 92,
    orderDate: "2026-08-29",
    timeline: [
      { step: "Order Placed", time: "10:15 AM", completed: true },
      { step: "Farmer Confirmed", time: "10:30 AM", completed: true },
      { step: "Produce Collected", time: "01:45 PM", completed: true },
      { step: "In Transit", time: "02:30 PM", completed: true, active: true },
      { step: "Delivered", time: "Est 04:30 PM", completed: false },
      { step: "Payment Settled", time: "Pending Verification", completed: false }
    ]
  }
];

const mockRythuBazaars = [
  {
    id: "rb-1",
    name: "Kankipadu Model Rythu Bazaar",
    location: "Main Road, Kankipadu",
    distanceKm: 3.2,
    activeStalls: 42,
    openHours: "5:30 AM - 1:00 PM & 4:00 PM - 8:00 PM",
    pickupSlotAvailable: true,
    featuredCrops: ["Tomato", "Palak", "Brinjal", "Green Chilli"]
  },
  {
    id: "rb-2",
    name: "Vijayawada Central Farmers Market",
    location: "Swaraj Maidan, Vijayawada",
    distanceKm: 8.5,
    activeStalls: 110,
    openHours: "5:00 AM - 9:00 PM",
    pickupSlotAvailable: true,
    featuredCrops: ["Red Chilli", "Carrot", "Onion", "Potato"]
  }
];

const mockPriceTrends = {
  Tomato: {
    today: 28,
    yesterday: 31,
    avg7Day: 32.5,
    predictedTomorrow: 30,
    demand: "HIGH",
    history: [35, 34, 33, 31, 30, 31, 28],
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  },
  Onion: {
    today: 34,
    yesterday: 33,
    avg7Day: 35.0,
    predictedTomorrow: 35,
    demand: "MODERATE",
    history: [36, 36, 35, 34, 33, 33, 34],
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  },
  Chilli: {
    today: 195,
    yesterday: 190,
    avg7Day: 188.0,
    predictedTomorrow: 198,
    demand: "VERY HIGH",
    history: [180, 182, 185, 187, 190, 190, 195],
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  }
};

const mockSetuForecastMatrix = {
  "Visakhapatnam": {
    "Kharif 2027": [
      { crop: "Tomato", icon: "🍅", demandPct: 92, demandLevel: "HIGH", priceTrend: "↑ (+18%)", priceTrendType: "up", score: 88, bestFit: "High Volume Buyers Nearby" },
      { crop: "Onion", icon: "🧅", demandPct: 85, demandLevel: "HIGH", priceTrend: "→ (+4%)", priceTrendType: "flat", score: 82, bestFit: "Urban Retail Hubs" },
      { crop: "Hot Chilli", icon: "🌶️", demandPct: 68, demandLevel: "MEDIUM", priceTrend: "↑ (+12%)", priceTrendType: "up", score: 74, bestFit: "Spice Exporters" },
      { crop: "Potato", icon: "🥔", demandPct: 42, demandLevel: "LOW", priceTrend: "↓ (-6%)", priceTrendType: "down", score: 52, bestFit: "Cold Storage Hold" }
    ],
    "Rabi 2026-27": [
      { crop: "Tomato", icon: "🍅", demandPct: 84, demandLevel: "HIGH", priceTrend: "↑ (+10%)", priceTrendType: "up", score: 81, bestFit: "Local Processing Hubs" },
      { crop: "Onion", icon: "🧅", demandPct: 90, demandLevel: "HIGH", priceTrend: "↑ (+15%)", priceTrendType: "up", score: 86, bestFit: "Wholesale Mandi Exporters" },
      { crop: "Brinjal", icon: "🍆", demandPct: 65, demandLevel: "MEDIUM", priceTrend: "→ (+2%)", priceTrendType: "flat", score: 70, bestFit: "District Fresh Markets" },
      { crop: "Potato", icon: "🥔", demandPct: 78, demandLevel: "HIGH", priceTrend: "↑ (+8%)", priceTrendType: "up", score: 76, bestFit: "Retail Chain Stores" }
    ],
    "Zaid 2027": [
      { crop: "Cucumber", icon: "🥒", demandPct: 94, demandLevel: "HIGH", priceTrend: "↑ (+22%)", priceTrendType: "up", score: 91, bestFit: "Summer Juice & Salad Supply" },
      { crop: "Tomato", icon: "🍅", demandPct: 75, demandLevel: "MEDIUM", priceTrend: "→ (+5%)", priceTrendType: "flat", score: 73, bestFit: "Urban Retail Hubs" },
      { crop: "Bitter Gourd", icon: "🥒", demandPct: 62, demandLevel: "MEDIUM", priceTrend: "↑ (+7%)", priceTrendType: "up", score: 68, bestFit: "Local Mandis" }
    ]
  },
  "Krishna": {
    "Kharif 2027": [
      { crop: "Tomato", icon: "🍅", demandPct: 89, demandLevel: "HIGH", priceTrend: "↑ (+15%)", priceTrendType: "up", score: 85, bestFit: "Vijayawada Wholesale Hub" },
      { crop: "Onion", icon: "🧅", demandPct: 82, demandLevel: "HIGH", priceTrend: "→ (+3%)", priceTrendType: "flat", score: 80, bestFit: "Coastal Retail Co-op" },
      { crop: "Hot Chilli", icon: "🌶️", demandPct: 72, demandLevel: "MEDIUM", priceTrend: "↑ (+9%)", priceTrendType: "up", score: 76, bestFit: "Regional Processors" },
      { crop: "Potato", icon: "🥔", demandPct: 45, demandLevel: "LOW", priceTrend: "↓ (-4%)", priceTrendType: "down", score: 55, bestFit: "Local Storage" }
    ]
  },
  "Guntur": {
    "Kharif 2027": [
      { crop: "Hot Chilli", icon: "🌶️", demandPct: 96, demandLevel: "VERY HIGH", priceTrend: "↑ (+24%)", priceTrendType: "up", score: 95, bestFit: "Mirchi Yard Export Clusters" },
      { crop: "Tomato", icon: "🍅", demandPct: 86, demandLevel: "HIGH", priceTrend: "↑ (+14%)", priceTrendType: "up", score: 84, bestFit: "Processing Plants" },
      { crop: "Onion", icon: "🧅", demandPct: 78, demandLevel: "MEDIUM", priceTrend: "→ (+5%)", priceTrendType: "flat", score: 77, bestFit: "Urban Markets" }
    ]
  },
  "East Godavari": {
    "Kharif 2027": [
      { crop: "Tomato", icon: "🍅", demandPct: 90, demandLevel: "HIGH", priceTrend: "↑ (+16%)", priceTrendType: "up", score: 87, bestFit: "Rajahmundry & Kakinada Hubs" },
      { crop: "Onion", icon: "🧅", demandPct: 88, demandLevel: "HIGH", priceTrend: "↑ (+11%)", priceTrendType: "up", score: 84, bestFit: "Coastal Traders" }
    ]
  }
};

const mockSetuDemandTrends = {
  Tomato: {
    labels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    demand: [320, 350, 410, 480, 520, 490, 440],
    supply: [280, 290, 310, 330, 340, 350, 360],
    peakDays: "Day 4 - Day 5 (Thu-Fri)",
    deficitWindow: "Day 3 to Day 5 (Deficit: ~180 Tons)",
    avgPrice: "₹28 - ₹34/kg"
  },
  Onion: {
    labels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    demand: [400, 420, 430, 450, 470, 460, 440],
    supply: [380, 390, 400, 410, 415, 420, 425],
    peakDays: "Day 5 (Friday)",
    deficitWindow: "Day 4 to Day 6 (Deficit: ~55 Tons)",
    avgPrice: "₹32 - ₹36/kg"
  },
  Brinjal: {
    labels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    demand: [150, 160, 180, 200, 220, 210, 190],
    supply: [160, 170, 185, 190, 200, 205, 200],
    peakDays: "Day 5 (Friday)",
    deficitWindow: "Day 4 to Day 5 (Minor Deficit: ~20 Tons)",
    avgPrice: "₹22 - ₹26/kg"
  },
  Capsicum: {
    labels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    demand: [180, 200, 230, 270, 300, 280, 240],
    supply: [140, 150, 160, 170, 180, 190, 195],
    peakDays: "Day 4 - Day 5",
    deficitWindow: "Day 3 to Day 6 (High Deficit: ~120 Tons)",
    avgPrice: "₹42 - ₹50/kg"
  },
  Ginger: {
    labels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    demand: [90, 95, 110, 125, 140, 135, 120],
    supply: [85, 90, 92, 95, 98, 100, 102],
    peakDays: "Day 5 (Friday)",
    deficitWindow: "Day 4 to Day 6 (Deficit: ~42 Tons)",
    avgPrice: "₹85 - ₹95/kg"
  }
};

